apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-configmap
  namespace: proxy-system
data:
  proxy.port: ":9443"
  proxy.target: "ulozto.cz"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpsproxy
  namespace: proxy-system
  labels:
    app: httpsproxy
  annotations:
    buildVersion: ${buildVersion}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpsproxy
  template:
    metadata:
      labels:
        app: httpsproxy
    spec:
      #pod must be running
      restartPolicy: Always
      containers:
        - name: httpsproxy
          image: acronhosbx.azurecr.io/htp:${tag}
          args:
            - -port=9443
            - -url=ulozto.cz
          #imagePullPolicy: Always: the image is pulled every time the pod is started.
          imagePullPolicy: Always
          volumeMounts:
            - name: httpsproxy
              mountPath: /etc/lb/certs
              readOnly: true
      volumes:
        - name: httpsproxy
          secret:
            secretName: httpsproxy-certs
---
apiVersion: v1
kind: Service
metadata:
  name: lb-svc
  namespace: proxy-system
  labels:
    app: httpsproxy
spec:
  ports:
    - port: 9443
      targetPort: 443
      name: https
  selector:
    app: httpsproxy
  type: LoadBalancer